#pragma once
#include <Windows.h>

#define ID_SCRRED 100
#define ID_SCRGREEN 101
#define ID_SCRBLUE 102

enum ENUM_SELECT_FIGURE {
	SELECT_FREELINE = 1000,
	SELECT_LINE,
	SELECT_RECTANGLE,
	SELECT_ROUNDRECT,
	SELECT_ELLIPSE,
	SELECT_TEXT,
	SELECT_ERASER,
	SELECT_NULL
};

enum ENUM_SELECT_TEXT {
	SELECT_NORMAL = 1000,
	SELECT_TRANSPARENT,
	SELECT_OPAQUE
};